list={ ...
      %'ZRmsSmall'...
      %'ZRms2Small'...
      %'DspRmsSmallLog'...
      %'DspRms2SmallLog'...
      'DSP2'...
      %'ZRms'...
      %'ZRms2'...
      %'nDvnReg', ...
      %'nDvnRegSmall', ...
      %'magDvnSmall' ...
      %'magDvn' ...
};

tic;
[MeAll,bStatus,tc,MSG]=ImapAll.queue(list{:});


if bStatus && toc(tc) > 60
    Email.sendSms(MSG,'MYJOBS: Imap queue');
end
